### ISSUE TITLE
[FEATURE REQUEST] Modify CopyComponentTo code-gen for better copying

### ISSUE THREAD

**Issue by jeffcampbellmakesgames** [jeffcampbellmakesgames/Entitas-Redux#16]
**Is your feature request related to a problem? Please describe.**
Currently the entity API `CopyComponentTo` performs a shallow copy of a component where a template instance's members's vales are assigned to a new component instance's members. This results in reference types being assigned directly, thus maintaining the reference instance of the same member between two different component instances. This includes members that are collections where the instance of the collection is assigned to both component instances. There is not currently an option that enables for deep copying a reference type member and/or copying the contents of a list to a new component collection member rather than assigning the collection itself.

**Describe the solution you'd like**
Ideally, the outcome of a reference type member on a component being copied should be:
* By default pass the member by reference.
    * For member types derived from `MonoBehaviour` or `ScriptableObject` (really anything from `UnityEngine.Object`) the intent is more likely to assign by ref since they usually don't have a default constructor or straightforward way to copy over all the instance data.
    * For member types that are plain-old CSharp objects, work from the developer is needed to copy over all required data on the component to a new instance, particularly where they could also contain Unity object member types.
* When a member reference type implements `ICloneable`, rather than assign the ref value directly call the `Clone` method on assignment to create a new separate instance of that ref type. By implementing `ICloneable` on a type used as a member on a component, in effect that will result in `CopyComponentTo` deep-copying the ref instance to a new one.
* When a member type is a collection:
    * If its an `IList`, `IReadOnlyList`, iterate over the list item in a for loop and assign/copy each member using these same default/`ICloneable`, collection rules.
    * If its not an `IList`, `IReadOnlyList`, iterate over the collection in a foreach loop and assign/copy each member using these same default/`ICloneable`, collection rules.

**Describe alternatives you've considered**
I'd like to avoid heavy usage of runtime reflection as much as possible to reduce down on the performance hit this operation should take (especially since it has the capacity to be used in bulk for many entities from blueprints). Any reflection that takes place should either be small or cached for reuse.

**Tasks**

- [x] Implement `ICloneable` on several example ref type components
- [x] Add `ICloneable` code-generation logic for `CopyComponentTo` method code-generator
- [x] Add `List` code-generation logic for `CopyComponentTo` method code-generator
- [x] Add `Array` code-generation logic for `CopyComponentTo` method code-generator
- [x] Add `Dictionary` code-generation logic for `CopyComponentTo` method code-generator
- [x] Add unit tests  for TypeExtensions to validate functionality
- [x] Add unit tests  for CopyComponentTo method to validate functionality
- [x] Update documentation

**Comment by jeffcampbellmakesgames** [comment]
Accomplished much of the implementation for a more nuanced copy logic for component members based on whether they are capable of supporting deep copy logic or not, looking to update/create unit tests and update documentation.

**Comment by jeffcampbellmakesgames** [comment]
This has been merged to develop.
